# Generated by Django 5.1.6 on 2025-02-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_app", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="choice",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="question",
            field=models.CharField(max_length=1000),
        ),
    ]
