# Generated by Django 5.1.6 on 2025-02-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_user_quiz_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_quiz_data',
            name='file_name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
