# Generated by Django 5.1.6 on 2025-02-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_user_quiz_data_file_name_delete_choice_delete_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_quiz_data',
            name='question_type',
            field=models.CharField(choices=[('MCQ', '객관식'), ('OX', 'O/X'), ('Short', '단답형')], default='MCQ', max_length=20),
        ),
    ]
