# Generated by Django 5.1.6 on 2025-02-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0009_user_quiz_data_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_quiz_data',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
