"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv  # dotenv 로드

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

OPEN_API_KEY= os.getenv("OPENAI_API_KEY")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$u2@)f1wpu_31d_&u%#62k6(*h==p*z5p)fxg4kdj%$bh_90^u"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# ==== env 파일 로드 
load_dotenv(BASE_DIR / ".env")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # 추가한 APPS
    'quiz_app',
    'accounts',
    'allauth',
    "django.contrib.sites",
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.kakao',
    'allauth.socialaccount.providers.naver',
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # allauth 미들웨어 추가
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        #"DIRS": [BASE_DIR / "templates"],  # 프로젝트 내 templates 폴더 사용
        'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'templates', 'account')],
        "APP_DIRS": True, # 각 앱의 templates 폴더도 포함
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",  # MySQL 엔진 사용
        "NAME": os.getenv("DATABASE_NAME"),  # 공유할 데이터베이스 이름
        "USER": os.getenv("DATABASE_USER"),  # DB 사용자명
        "PASSWORD": os.getenv("DATABASE_PASSWORD"),  # DB 비밀번호
        "HOST": os.getenv("DATABASE_HOST"),  # 로컬 호스트
        "PORT": os.getenv("DATABASE_PORT"),  # MySQL 기본 포트
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    
]

# Provider specific settings
# ==== 🔗 소셜 로그인 제공자 설정 ====
SOCIALACCOUNT_PROVIDERS = {
    "naver": {
        "APP": {
            "client_id":os.getenv("NAVER_CLIENT_ID"),
            "secret":os.getenv("NAVER_SECRET"),
            "key": "",
        },
    },
    "kakao": {
        "APP": {
            "client_id": os.getenv("KAKAO_CLIENT_ID"),
            "secret": "",
            "key": "",
        },
        "AUTH_PARAMS": {"prompt": "login"},  # 로그인 창 강제 띄우기
    },
    "google": {
        "APP": {
            "client_id": os.getenv("GOOGLE_CLIENT_ID"),
            "secret": os.getenv("GOOGLE_SECRET"),
            "key": "",
        },
        "SCOPE": ["profile", "email"],  # Google에서 가져올 정보
        "AUTH_PARAMS": {
            "access_type": "offline",  # refresh_token 유지 (자동 로그인 지원)
            "prompt": "select_account",  # 계정 선택 창 띄우기
        },
    },
}

# ==== 추가 코드 ==== 

AUTH_USER_MODEL = "accounts.User"
LOGIN_REDIRECT_URL = '/'
#LOGIN_REDIRECT_URL = '/' # 로그인 리다이렉트 url 설정

# # 회원가입 또는 비밀번호 찾기를 할 때 이메일을 전송해 인증
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend" 

# # 디폴트값으로는 username을 통해 로그인하게 되어 있습니다
# #ACCOUNT_AUTHENTICATION_METHOD = "email"
# ACCOUNT_LOGIN_METHODS = {'email'}

# # 회원가입 시 아이디 입력을 받지 않고 이메일만 입력을 받고 싶다면
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_USERNAME_REQUIRED = False

# #브라우저를 닫아도 세션 쿠키를 유지할 것인지 삭제할 것인지를 정해주는 기능
# ACCOUNT_SESSION_REMEMBER = True

# # 쿠키의 유지 시간
# SESSION_COOKIE_AGE = 3600

# # 로그아웃 링크를 누르자마자 바로 로그아웃
# ACCOUNT_LOGOUT_ON_GET = True

# #해당 signup폼을 사용하겠다는 설정
# #ACCOUNT_SIGNUP_FORM_CLASS = "login2.forms.SignupForm"

# # 비밀번호 유효성 클래스를 추가합니다.
# AUTH_PASSWORD_VALIDATORS = [
#     {"NAME": "accounts.validators.CustomPasswordValidator"},
# ]
# # 회원가입 폼이 유효하지 않아도 폼에 작성했던 내용을 모두 지우지 않고 입력했던 비밀번호를 그대로 유지
# ACCOUNT_PASSWORD_INPUT_RENDER_VALUE = True

# # 이메일 인증 설정
# ACCOUNT_EMAIL_VARIFICATION = "mandatory"    # 인증을 안하면 로그인 자체를 못합니다
# #ACCOUNT_EMAIL_VARIFICATION = "optional"	    # 메일은 발송되지만 이메일을 인증안해도 로그인은 됩니다 -> 기본값
# #ACCOUNT_EMAIL_VARIFICATION = "none"	        # 아예 이메일 인증 자체를 안합니다

# # 이메일로 전송된 링크를 누르면 바로 회원가입이 완료됩니다
# ACCOUNT_CONFIRM_EMAIL_ON_GET = True

# ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "account_email_confirmation"
# ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "account_email_confirmation"

# # 비밀번호 재설정 링크의 유효기간 설정
# # django 3.1 이후 버전 (단위: 초) 
# PASSWORD_RESET_TIMOUT = 100000

